### ISSUE TITLE
Cant run the Example because of a Assertion Error 

### ISSUE THREAD

**Issue by XgatorX** [spMohanty/marLo#85]
Hey guys sorry to bother you, but I wanted to use this API as Part of my Master Thesis. I installed everything with Conda but can't even run the example code, because of that error:
![image](https://github.com/crowdAI/marLo/assets/165187087/97bc0b93-b68c-4c6c-b9cc-02a891afb446)
I can't find a Solution, hope you can help, thanks !

**Comment by troydutton** [comment]
I have the same issue. Is there a specific version of gym that we're supposed to use?

**Comment by XgatorX** [comment]
I don't know. With the conda install, all version conflicts should be solved, or am I mistaken? I didn't find a solution online, and I tried every OS; everywhere the same error. I am using Malmo now, but it is a lot slower than Marlo. :/ If you find a solution to the problem, please post it here.

**Comment by troydutton** [comment]
Found the fix. Install gym=0.19. You might run into some issues after that, lmk if you do.

**Comment by XgatorX** [comment]
Yeah that fix worked THANKS ! I run in that Problem with the Multiagent Example. 
![image](https://github.com/crowdAI/marLo/assets/165187087/2df11353-f646-4ccd-b8cd-c4e576f1fd31)
do you have the same Issue ? 
I can now run the Single Agent Example without Problems !

**Comment by XgatorX** [comment]
Ok Solved the Issue with the help of issue #76. Now I ran into the issue #84.
